#include <stdio.h>
#include <stdlib.h>
#include "git.c" // 假设你定义的 libgit2 封装函数都在 git.c 里

int main()
{
    const char *url = "https://github.com/xxxxxx/xxxxxxxxx.git";
    const char *dir = "test_clone";

    printf("🚀 Cloning repo from %s ...\n", url);
    void *repo = mb_git_clone(url, dir);
    if (!repo)
    {
        printf("❌ Clone failed\n");
        return 1;
    }
    printf("✅ Cloned repo pointer: %p\n", repo);

    // ===== 写入一个测试文件 =====
    char file_path[256];
    snprintf(file_path, sizeof(file_path), "%s/test_file.md", dir);
    FILE *fp = fopen(file_path, "w");
    if (!fp)
    {
        perror("❌ Failed to write test file");
        mb_git_free(repo);
        return 1;
    }
    fprintf(fp, "# Test Commit from C\n\nThis file was generated by libgit2 test.\n");
    fclose(fp);
    printf("✅ Wrote test file: %s\n", file_path);

    // ===== 添加文件 =====
    printf("🧩 Adding file...\n");
    int add_res = mb_git_add(repo, "test_file.md");
    if (add_res != 0)
    {
        printf("❌ Add failed: %d\n", add_res);
        mb_git_free(repo);
        return 1;
    }
    printf("✅ File added.\n");

    // ===== 提交 =====
    printf("🪶 Committing...\n");
    int commit_res = mb_git_commit(repo, "Test commit from C using libgit2");
    if (commit_res != 0)
    {
        printf("❌ Commit failed: %d\n", commit_res);
        mb_git_free(repo);
        return 1;
    }
    printf("✅ Commit success.\n");

    // ===== 推送 =====
    const char *token = "ghp_2xxxxxxxxxxxxxxxxxxxxxxxxxx"; // ⚠️ 确保是有效 token
    printf("🚀 Pushing to GitHub...\n");

    int push_res = mb_git_push(repo, "origin", token);
    if (push_res == 0)
    {
        printf("✅ Push success!\n");
    }
    else
    {
        printf("❌ Push failed, code=%d\n", push_res);
    }

    // ===== 清理 =====
    printf("🧹 Freeing repo...\n");
    mb_git_free(repo);
    printf("✅ Done.\n");

    return 0;
}
